### PR TITLE
added setTitleProps to send props to custom components

### PR DESCRIPTION
**Pull request by davide-scalzo**
As per issue #16 I needed to pass props to the custom title component, this PR adds setTitleProps to pass props to the titleComponent.

### CODE REVIEW

**Comment by MikaelCarpenter** [comment]
looks good man! thanks for the contribution

**Comment by davide-scalzo** [comment]
My pleasure :)

**Comment by davide-scalzo** [comment]
Somehow, the changes to index.js have been lost..

**Comment by davidLeonardi** [comment]
Seems to be my fault :(
I'm busy now, will check tomorrow morning if i mistakenly removed other commits as well.
I suspect this is because I had developed against an slightly older checkout.
I'll add your code in back tomorrow again, or feel free to re-PR your change, either works fine.

**Pull request merged**
