### PR TITLE
Expensive view

### PR DESCRIPTION
**Pull request by AnNOtis**

### CODE REVIEW

**Comment by davidLeonardi** [comment]
Wow, thanks for this!

**Comment by davidLeonardi** [comment]
Anyhow, plase add semicolons to end of lines.
I feel like that should be standard javascript convention by now to respect
the actual grammar of the language.

**Comment by davidLeonardi** [comment]
@AnNOtis would you like to contribute this to https://github.com/react-native-simple-router-community/react-native-simple-router ?

**Comment by AnNOtis** [comment]
Apologize for the delay. These PR is a mistake, the code is not ready to public. It just be used for our team's internal usage. Didn't take care of stability.

I'm glad to open another PR to new repo after some works. :sunglasses:

**Comment by AnNOtis** [comment]
I start to give it a try when I found some popular [style](https://github.com/feross/standard) [configs](https://github.com/rackt/eslint-config-rackt) ignore semicolons.
But I don't persevere at it. It's just preference.

**Pull request closed without merging**
